### PR TITLE
[201.6668] Updated to work with Intellij 2020.1 201.6668.

### PR DESCRIPTION
**Pull request by h3adache**
# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: #1567

# Description of this change

I updated the code simply to fix issues caused by api changes in Intellij.
~~This doesn't address the single runtime issue that does not affect the plugin.~~
This builds with `intellij-canary` and `intellij-ue-canary`.

### CODE REVIEW

**Comment by unoexperto** [comment]
@h3adache Could you please advise how to build this ?

```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-canary
```

and 

```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-canary
```

fail with following error

```
ERROR: /home/expert/work/sideprojects/bazel-plugin/ijwb/BUILD:41:1: in cmd attribute of genrule rule //ijwb:stamped_plugin_xml_api_version: label '//intellij_platform_sdk:application_info_jar' in $(location) expression expands to no files. Since this rule was created by the macro 'stamped_plugin_xml', the error might have been caused by the macro implementation
ERROR: Analysis of target '//ijwb:ijwb_bazel_zip' failed; build aborted: Analysis of target '//ijwb:stamped_plugin_xml_api_version' failed; build aborted

```

**Comment by h3adache** [comment]
> @h3adache Could you please advise how to build this ?
> 
> ```
> bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-canary
> ```
> 
> and
> 
> ```
> bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-canary
> ```
> 
> fail with following error
> 
> ```
> ERROR: /home/expert/work/sideprojects/bazel-plugin/ijwb/BUILD:41:1: in cmd attribute of genrule rule //ijwb:stamped_plugin_xml_api_version: label '//intellij_platform_sdk:application_info_jar' in $(location) expression expands to no files. Since this rule was created by the macro 'stamped_plugin_xml', the error might have been caused by the macro implementation
> ERROR: Analysis of target '//ijwb:ijwb_bazel_zip' failed; build aborted: Analysis of target '//ijwb:stamped_plugin_xml_api_version' failed; build aborted
> ```

Hi I'm sorry @unoexperto. Make sure to check out branch `201.6668` from my repository.
```
➜  ~/tmp/intellij (master) ✔ git checkout 201.6668
```
After that if it still errors run
```
bazel clean --expunge
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-canary
```
Strange behavior that I haven't had time to track down is that if you import a bazel project, sometimes the project view doesn't show up even after it indexes.

If that happens to you just close and reopen the project.

**Comment by AnatolyRugalev** [comment]
I tried to build it but it seems like the IDEA distribution was removed from the public:
```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-canary
...
WARNING: Download from https://download.jetbrains.com/idea/ideaIC-201.4515.24.tar.gz failed: class java.io.IOException GET returned 403 Forbidden
ERROR: An error occurred during the fetch of repository 'intellij_ce_2020_1':
   java.io.IOException: Error downloading [https://download.jetbrains.com/idea/ideaIC-201.4515.24.tar.gz] to /home/anatoly/.cache/bazel/_bazel_anatoly/b9de904b3a5015418f00840849169bb5/external/intellij_ce_2020_1/ideaIC-201.4515.24.tar.gz: GET returned 403 Forbidden
...
```
This patch fixed downloading stage but another issue arose:
```
diff --git a/WORKSPACE b/WORKSPACE
index 1aef3cb8..cef11e0f 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -55,8 +55,8 @@ http_archive(
 http_archive(
     name = "intellij_ue_2020_1",
     build_file = "@//intellij_platform_sdk:BUILD.ue201",
-    sha256 = "0944d1b15e6d8d8c13e33ed0bb43773bf7a2cd2100a679c2a668d543a7931de8",
-    url = "https://download-cf.jetbrains.com/idea/ideaIU-201.4515.24.tar.gz",
+    sha256 = "ca485decf8b91549a1c8e20309a7a7b6a7e032ff96e10fde2ff5dbae9e0108e3",
+    url = "https://download-cf.jetbrains.com/idea/ideaIU-2020.1.1.tar.gz",
 )
```

```
ERROR: /home/anatoly/projects/intellij/ijwb/BUILD:41:1: in cmd attribute of genrule rule //ijwb:stamped_plugin_xml_api_version: label '//intellij_platform_sdk:application_info_jar' in $(location) expression expands to no files. Since this rule was created by the macro 'stamped_plugin_xml', the error might have been caused by the macro implementation
ERROR: Analysis of target '//ijwb:ijwb_bazel_zip' failed; build aborted: Analysis of target '//ijwb:stamped_pluginI'd like to h_xml_api_version' failed
```

**Comment by AnatolyRugalev** [comment]
Ok, I replaced it with zip versions from different location and it stuck on another error now:

```
diff --git a/WORKSPACE b/WORKSPACE
index 1aef3cb8..ff70b44c 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -28,8 +28,8 @@ http_archive(
 http_archive(
     name = "intellij_ce_2020_1",
     build_file = "@//intellij_platform_sdk:BUILD.idea201",
-    sha256 = "396f0045a713f224015c082924fc5c71be0e029effa2fd7bd3fa65632a55a18c",
-    url = "https://download.jetbrains.com/idea/ideaIC-201.4515.24.tar.gz",
+    sha256 = "4f3333eeee617b2fc624292007c753a78092d5eff1dca3d94f9d3aae6bd0e6c2",
+    url = "https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.1/ideaIC-2020.1.1.zip",
 )
 
 # The plugin api for IntelliJ UE 2019.2. This is required to run UE-specific
@@ -55,8 +55,8 @@ http_archive(
 http_archive(
     name = "intellij_ue_2020_1",
     build_file = "@//intellij_platform_sdk:BUILD.ue201",
-    sha256 = "0944d1b15e6d8d8c13e33ed0bb43773bf7a2cd2100a679c2a668d543a7931de8",
-    url = "https://download-cf.jetbrains.com/idea/ideaIU-201.4515.24.tar.gz",
+    sha256 = "7d52479c8f3db7cf4a917accec9b120c7daa9d4b3cfe423d3369c3a2fe379808",
+    url = "https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2020.1.1/ideaIU-2020.1.1.zip",
 )
 ```
```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-canary
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //ijwb:ijwb_bazel_zip (66 packages loaded, 2123 targets configured).
INFO: Found 1 target...
ERROR: /home/anatoly/projects/intellij/sdkcompat/v201/BUILD:7:1: Building sdkcompat/v201/libv201.jar (23 source files) failed (Exit 1)
sdkcompat/v201/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java:23: error: cannot find symbol
import com.intellij.serviceContainer.PlatformComponentManagerImpl;
                                    ^
  symbol:   class PlatformComponentManagerImpl
  location: package com.intellij.serviceContainer
sdkcompat/v201/com/google/idea/sdkcompat/general/BaseSdkCompat.java:40: error: incompatible types: ProjectExtensionPointName<Provider<?>> cannot be converted to ProjectExtensionPointName<Provider>
    return EditorNotificationsImpl.EP_PROJECT;
                                  ^
sdkcompat/v201/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java:45: error: cannot find symbol
    ((PlatformComponentManagerImpl) componentManager)
      ^
  symbol:   class PlatformComponentManagerImpl
  location: class ServiceHelperCompat
```

**Comment by AnatolyRugalev** [comment]
After poking things around I came up with this patch:
```
Index: WORKSPACE
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- WORKSPACE	(revision fcfc098fec89b21ea3a32b3f40bf72aa1b5ca00a)
+++ WORKSPACE	(date 1589114781142)
@@ -28,8 +28,8 @@
 http_archive(
     name = "intellij_ce_2020_1",
     build_file = "@//intellij_platform_sdk:BUILD.idea201",
-    sha256 = "396f0045a713f224015c082924fc5c71be0e029effa2fd7bd3fa65632a55a18c",
-    url = "https://download.jetbrains.com/idea/ideaIC-201.4515.24.tar.gz",
+    sha256 = "4f3333eeee617b2fc624292007c753a78092d5eff1dca3d94f9d3aae6bd0e6c2",
+    url = "https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2020.1.1/ideaIC-2020.1.1.zip",
 )
 
 # The plugin api for IntelliJ UE 2019.2. This is required to run UE-specific
@@ -55,8 +55,8 @@
 http_archive(
     name = "intellij_ue_2020_1",
     build_file = "@//intellij_platform_sdk:BUILD.ue201",
-    sha256 = "0944d1b15e6d8d8c13e33ed0bb43773bf7a2cd2100a679c2a668d543a7931de8",
-    url = "https://download-cf.jetbrains.com/idea/ideaIU-201.4515.24.tar.gz",
+    sha256 = "7d52479c8f3db7cf4a917accec9b120c7daa9d4b3cfe423d3369c3a2fe379808",
+    url = "https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIU/2020.1.1/ideaIU-2020.1.1.zip",
 )
 
 # The plugin api for CLion 2019.2. This is required to build CLwB,
Index: base/src/com/google/idea/blaze/base/settings/ui/AddDirectoryToProjectAction.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- base/src/com/google/idea/blaze/base/settings/ui/AddDirectoryToProjectAction.java	(revision fcfc098fec89b21ea3a32b3f40bf72aa1b5ca00a)
+++ base/src/com/google/idea/blaze/base/settings/ui/AddDirectoryToProjectAction.java	(date 1589116658637)
@@ -130,7 +130,7 @@
           WorkspaceFileTextField.create(
               workspacePathResolver, descriptor, PATH_FIELD_WIDTH, myDisposable);
       JBLabel directoryLabel =
-          new JBLabel("Directory:", AllIcons.Modules.SourceFolder, SwingConstants.LEFT);
+          new JBLabel("Directory:", AllIcons.Modules.SourceRoot, SwingConstants.LEFT);
       JPanel directoryPanel =
           SwingHelper.newHorizontalPanel(
               Component.TOP_ALIGNMENT, directoryLabel, fileTextField.getField());
Index: java/src/com/google/idea/blaze/java/libraries/DisableLibraryBytecodeNotification.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- java/src/com/google/idea/blaze/java/libraries/DisableLibraryBytecodeNotification.java	(revision fcfc098fec89b21ea3a32b3f40bf72aa1b5ca00a)
+++ java/src/com/google/idea/blaze/java/libraries/DisableLibraryBytecodeNotification.java	(date 1589115763191)
@@ -40,7 +40,7 @@
     if (!enabled.getValue() || !Blaze.isBlazeProject(project)) {
       return;
     }
-    ProjectExtensionPointName<Provider> epName = BaseSdkCompat.getEditorNotificationsEp();
+    ProjectExtensionPointName<Provider<?>> epName = BaseSdkCompat.getEditorNotificationsEp();
     if (epName == null) {
       return;
     }
Index: java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildDebugExecutor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildDebugExecutor.java	(revision fcfc098fec89b21ea3a32b3f40bf72aa1b5ca00a)
+++ java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildDebugExecutor.java	(date 1589116394915)
@@ -69,7 +69,7 @@
 
   @Override
   public Icon getDisabledIcon() {
-    return new LayeredIcon(AllIcons.Process.DisabledDebug, BlazeIcons.LightningOverlay);
+    return new LayeredIcon(AllIcons.Actions.StartDebugger, BlazeIcons.LightningOverlay);
   }
 
   @Override
Index: sdkcompat/v201/com/google/idea/sdkcompat/general/BaseSdkCompat.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sdkcompat/v201/com/google/idea/sdkcompat/general/BaseSdkCompat.java	(revision fcfc098fec89b21ea3a32b3f40bf72aa1b5ca00a)
+++ sdkcompat/v201/com/google/idea/sdkcompat/general/BaseSdkCompat.java	(date 1589115694318)
@@ -36,7 +36,7 @@
 
   /** #api193: made public in 2020.1. */
   @SuppressWarnings("rawtypes")
-  public static ProjectExtensionPointName<EditorNotifications.Provider> getEditorNotificationsEp() {
+  public static ProjectExtensionPointName<EditorNotifications.Provider<?>> getEditorNotificationsEp() {
     return EditorNotificationsImpl.EP_PROJECT;
   }
 
Index: java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildRunExecutor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildRunExecutor.java	(revision fcfc098fec89b21ea3a32b3f40bf72aa1b5ca00a)
+++ java/src/com/google/idea/blaze/java/run/fastbuild/FastBuildRunExecutor.java	(date 1589116464974)
@@ -67,7 +67,7 @@
 
   @Override
   public Icon getDisabledIcon() {
-    return new LayeredIcon(AllIcons.Process.DisabledRun, BlazeIcons.LightningOverlay);
+    return new LayeredIcon(AllIcons.Actions.Execute, BlazeIcons.LightningOverlay);
   }
 
   @Override
Index: sdkcompat/v201/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sdkcompat/v201/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java	(revision fcfc098fec89b21ea3a32b3f40bf72aa1b5ca00a)
+++ sdkcompat/v201/com/google/idea/sdkcompat/platform/ServiceHelperCompat.java	(date 1589115500952)
@@ -20,7 +20,7 @@
 import com.intellij.ide.plugins.PluginManager;
 import com.intellij.openapi.Disposable;
 import com.intellij.openapi.components.ComponentManager;
-import com.intellij.serviceContainer.PlatformComponentManagerImpl;
+import com.intellij.serviceContainer.ComponentManagerImpl;
 import java.util.List;
 import java.util.Optional;
 
@@ -42,7 +42,7 @@
 
     Verify.verify(platformPlugin.isPresent());
 
-    ((PlatformComponentManagerImpl) componentManager)
+    ((ComponentManagerImpl) componentManager)
         .registerServiceInstance(key, implementation, platformPlugin.get());
   }
 
```

It seems like there was some extra API changes after EAP. The most breaking change is missing icons, so I replaced them with not-so-appropriate alternatives, please be aware of that.

Trying to install plugin now to UE

**Comment by AnatolyRugalev** [comment]
I imported plugin into my IDEA Ultimate 2020.1.1 and it kinda works.

This is IDEA 2020.1.1 compatible plugins:
UE: https://mega.nz/file/WYsBGSLR#3GqzUNUvP3W-UPOH9qvEVRc_jbA_jKmdkAE6jteWpX4
CE: https://mega.nz/file/yQsFwAyS#JARbhJpznKff3EIT5MpAcVS99mRZKTfwWNOD04MRZ_U

I genuinely don't know if there is any difference between this two builds, but I built both of them.

**Comment by AnatolyRugalev** [comment]
Also, I can't see Bazel menu. I can find it in menu configuration but can't do anything with it:

image

**Comment by h3adache** [comment]
@AnatolyRugalev I'm sorry I don't think you are building off the correct branch.
The branch is `201.668` in my repo I did not put it on my `own master`

The bazel menu should look like this with my patch.
Screen Shot 2020-05-12 at 12 24 15 PM

**Comment by AnatolyRugalev** [comment]
@h3adache ah sorry, I definitely missed that. What a waste of time!

Thank you, will try that

**Comment by sromocki** [comment]
Will this PR merge make the Bazel plugin compatible with IntelliJ 2020.1?  If so, can this be merged?

**Comment by h3adache** [comment]
@sromocki looks like @brendandouglas who is on this review pushed his own changes for Intellij 2020 so this is probably not needed or going to be merged.

**Comment by nkoroste** [comment]
Can you link to the PR?

**Comment by alice-ks** [comment]
Thanks for having sent this PR. Closing as it's obsolete by now.

**Pull request closed without merging**
