### PR TITLE
[JavaInfo] use transitive_runtime_jars if compilation_info is None

### PR DESCRIPTION
**Pull request by ittaiz**
# Checklist

- [V ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ X] I have received the approval from the maintainers to make this change.
- [V ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: https://github.com/bazelbuild/intellij/issues/1281

# Description of this change
Use transitive_runtime_jars if compilation_info is None

### CODE REVIEW

**Comment by brendandouglas** [comment]
Thanks for tracking this down. I'll apply it upstream, though I hope Bazel will fix this at some point.

**Comment by KaoruDev** [comment]
@brendandouglas just following up, seems like this PR didn't get merged, seems to fix the issue I'm seeing with: https://github.com/bazelbuild/intellij/issues/1490

**Comment by brendandouglas** [comment]
It's merged at head, expressed slightly differently but equivalently. I'd guess you're on a build from before Nov 5th 2019?

**Comment by brendandouglas** [comment]
Sorry no you're right, it's fixed upstream, but somehow the fix wasn't applied to this github repo.

I'll take a look.

**Comment by brendandouglas** [comment]
And now the fix appears fully applied at head on github, as of November 5th 2019. Not sure what I was looking at yesterday.

**Pull request closed without merging**
