### PR TITLE
Update changelog for v2024.12.17 release

### PR DESCRIPTION
**Pull request by satyanandak**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by ujohnny** [comment]
#7143
#7139
#7146
#7167
#7159

**Comment by ujohnny** [comment]
@LeFrosch lets add your today contributions here too

**Comment by LeFrosch** [comment]
#7062 (not sure if this was already released) and #7141
#7100
#7094 (but not sure if we should announce this yet since qsync is still experimental in CLion)

**Comment by mai93** [comment]
### Fixes:
- https://github.com/bazelbuild/intellij/pull/7143
- https://github.com/bazelbuild/intellij/pull/7139
- https://github.com/bazelbuild/intellij/pull/7146
- https://github.com/bazelbuild/intellij/pull/7167
- https://github.com/bazelbuild/intellij/pull/7159

### Features:
- https://github.com/bazelbuild/intellij/pull/7062
- https://github.com/bazelbuild/intellij/pull/7141
- https://github.com/bazelbuild/intellij/pull/7100
- Experimental: https://github.com/bazelbuild/intellij/pull/7094

**Review by mai93 — APPROVED** [review]

**Comment by ujohnny** [comment]
@satyanandak can we postpone the release until tomorrow? I'd like to fix bazel 8 relates issue.

**Comment by ujohnny** [comment]
v2024.12.17 is ok. v2024.12.03 requires #7183 to be merged

**Pull request merged**
