### PR TITLE
Adapt paths and line breaks for Windows

### LINKED ISSUE #5470: Loading workspaces fails on Windows
### Description of the bug:

Selecting a file path under 'Copy external' throws the error due to line-breaks:
`java.lang.AssertionError: Wrong line separators: '...rectories:\r\n  .\r\n  -...' at offset 12`
While selecting the same file under 'Import project view file' throws and error saying that the file path is not under the project path. The cause of this error is that the view file has front slashes while the directory path has back slashes.
I've already created a fix for both of these problems and I expect them to be compatible with all other operating systems.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On Windows try to open a view file.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2023.3 EAP (Ultimate Edition) Build #IU-233.9102.97, built on October 4, 2023

### What programming languages and tools are you using? Please provide specific versions.

Java with JDK 17

### What Bazel plugin version are you using?

Latest master branch (4e4631a)

### Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by ahmedyarub**
Fix typos

# Checklist

- [X] I have filed an issue about this change and discussed potential changes with the maintainers.
- [X] I have received the approval from the maintainers to make this change.
- [X] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `5470`

# Description of this change
Fix directory separators and line-breaks on Windows, and fix some typos.

Closes #5470

### CODE REVIEW

**Comment by sgowroji** [comment]
Hi @ahmedyarub, Could you please sign the CLA?

**Review by agluszak — APPROVED** [review]

**Comment by agluszak** [comment]
> I would run both replacements conditionally, only for non-WSL WIndows. In unix systems you can have backslash in a filename (try `mkdir a\\b`).
> 
> Same story for `\r`, just because it's not required outside Windows

Good catch

**Comment by ahmed-nuaimi** [comment]
This one is still tagged with Awaiting user response. Do I need to do anything?

**Comment by ahmedyarub** [comment]
Do I need to add anything here?

**Review by blorente — APPROVED** [review]
Thanks for adding the changes!
Please note that CI doesn't run on Windows, so it might break in the future.

**Comment by ahmedyarub** [comment]
> Thanks for adding the changes! Please note that CI doesn't run on Windows, so it might break in the future.

Just tag me anytime a bug is reported and I'll make sure to fix it ASAP. I appreciate this great project really!

**Pull request merged**
