### PR TITLE
Fix Bazel CI tests

### PR DESCRIPTION
**Pull request by brendandouglas**
- turn off aspect tests on macs
- temporarily turn off set/depset enforcement in skylark
(until we build against rules_scala head)

### CODE REVIEW

**Comment by ittaiz** [comment]
Brendan,
If you build against rules_scala HEAD then the tests fail?

**Comment by brendandouglas** [comment]
Last I checked, there was an ijar-related failure running against rules_scala HEAD.

**Comment by ittaiz** [comment]
Is there a public link for me to look?

**Comment by brendandouglas** [comment]
No public link, but it should be reproducible by:
- pointing the WORKSPACE rule to rules_scala HEAD
- running 'bazel test //aspect/testing/...'

**Comment by ittaiz** [comment]
Right :)
I'll see if I get around to it

**Pull request merged**
