### PR TITLE
Update intellij 2020_2 versions

### PR DESCRIPTION
**Pull request by software-engineering**
Update version from 2020.2.2 to 2020.2.3

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by software-engineering** [comment]
@googlebot I signed it!

**Comment by software-engineering** [comment]
Before I send the PR I have several problems to generate the Plugin for IJ Ultimate myself ...

Issue: https://github.com/bazelbuild/intellij/issues/1792

Build with docker as described:
https://kig.re/2020/03/21/building-intellij-bazel-plugin.html

root@da118a938287:/src/workspace# bash build.sh intellij-2020.2
Get following Error:
ERROR: An error occurred during the fetch of repository 'python_2020_2':
   Traceback (most recent call last):
	File "/tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://plugins.jetbrains.com/files/7322/97141/python-ce-202.7319.64.zip] to /tmp/build_output/a08c2e4811c846650b733c6fc815a920/external/python_2020_2/python-ce-202.7319.64.zip: Checksum was 61eb876781f3fd75f2d9e76cac192672a02e008725ad9d7ac0fbd4e3dcf25b16 but wanted fa9524db2f5b6e42be559ffdab73a963ca06ca057e27a290f5665d38e581764a
... other Errors

next error
root@da118a938287:/src/workspace# bash build.sh intellij-ue-2020.2
ERROR: /src/workspace/golang/BUILD:16:13: Building golang/libgolang.jar (22 source files) failed (Exit 1)
...

Hope the build runs and i get the plugin for intellij

**Comment by c16a** [comment]
@vsiva @chaoren @brendandouglas  - can this be merged please?

**Comment by brendandouglas** [comment]
Thanks for the PR -- this will need to be done internally however, since this bazel-specific change is only part of a larger update process to our internal code base.

**Pull request closed without merging**
