### PR TITLE
fixed file hyperlinks from the zinc compiler

### PR DESCRIPTION
**Pull request by CreepyMob**
# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [x] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `https://github.com/bazelbuild/intellij/issues/1240`

# Description of this change

add ZincParser for parse specific issue format + test

### CODE REVIEW

**Comment by Odomontois** [comment]
@vsiva @chaoren @brendandouglas 
Can you look into this?

**Comment by chaoren** [comment]
Is there no way to just change the output to match the default scala compiler from the tool end? It's not really scalable to add every quirk of every variant compiler.

**Comment by sgowroji** [comment]
Hello @CreepyMob, Could you please resolve the above code conflicts. Thanks!

**Comment by keertk** [comment]
Hi there! Thank you for contributing to the IntelliJ repository. We appreciate your time and effort. We're doing a clean up of old PRs and will be closing this one since it seems to have stalled. Please feel free to reopen/let us know if you’re still interested in pursuing this or if you'd like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Pull request closed without merging**
