### PR TITLE
chore: Bump Bazel version

### PR DESCRIPTION
**Pull request by tpasternak**
applied recommendation from here: https://github.com/bazelbuild/intellij/issues/7058#issuecomment-2511377364

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by tpasternak** [comment]
@iancha1992 something is wrong with buildkite, could you please take a look?

**Comment by mai93** [comment]
@tpasternak I retried the failing tests and we may need to check the asserts in some tests:
[Log for intellij-plugin-aspect](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/01938899-00ba-45da-9365-7e9cbb200fec/aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl/JavaProtoLibraryTest/test_attempts/attempt_1.log)
[Log for intellij-ue-plugin](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/019388c6-5397-47c4-ab65-d01067ebf1b8/querysync/javatests/com/google/idea/blaze/qsync/project/BuildGraphDataTest/test_attempts/attempt_1.log)

**Comment by tpasternak** [comment]
thank you @mai93 

update:
for `jpl:bar_java_proto` a `JavaRuleOutputJarsProvider$JavaOutput` in bazel 8, but not bazel 7

**Comment by tpasternak** [comment]
In bazel8:
```
bazel cquery --output=starlark "--starlark:expr=providers(target)['@@rules_java+//java/private:java_info.bzl%JavaInfo'].java_outputs" //aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl:bar_java_proto 

[<unknown object com.google.devtools.build.lib.rules.java.JavaRuleOutputJarsProvider$JavaOutput>]
```

in bazel7:
```
bazel cquery --output=starlark "--starlark:expr=providers(target)['@@_builtins//:common/java/java_info.bzl%JavaInfo'].java_outputs" //aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl:bar_java_proto 

[]
```

**Comment by tpasternak** [comment]
For the context - the failing test is here, and there's an explicit comment about it

https://github.com/bazelbuild/intellij/blob/8581c5f9d3ea41175eb42dbceaa18b97a3edb850/aspect/testing/tests/src/com/google/idea/blaze/aspect/proto/jpl/JavaProtoLibraryTest.java#L46-L47

**Comment by tpasternak** [comment]
https://github.com/bazelbuild/bazel/issues/24543

**Pull request closed without merging**
