### PR TITLE
Update Issues and PRs Assignees

### PR DESCRIPTION
**Pull request by mai93**

### CODE REVIEW

**Comment by mai93** [comment]
@sgowroji are there other places (in workflows or documents) where we need to update the assignees?

**Comment by mai93** [comment]
@tpasternak did I get the mappings right?

**Review by ujohnny — APPROVED** [review]
lgtm

**Comment by mai93** [comment]
@iliakondratev @sellophane @agluszak can we get your approval on this assignment?

**Review by iliakondratev — APPROVED** [review]

**Pull request merged**
