### PR TITLE
Update changelog for v2024.08.27 release

### PR DESCRIPTION
**Pull request by satyanandak**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by mai93** [comment]
## Features
- https://github.com/bazelbuild/intellij/pull/6615
- https://github.com/bazelbuild/intellij/pull/6595

## Bug Fixes
- https://github.com/bazelbuild/intellij/pull/6645
- https://github.com/bazelbuild/intellij/pull/6634

**Comment by tpasternak** [comment]
I would only reword #6634  to "go: fix testify single test execution"

**Comment by tpasternak** [comment]
Also, we could add this if we managed to merge it 
- https://github.com/bazelbuild/intellij/pull/6665

**Comment by satyanandak** [comment]
Hi @tpasternak @mai93,
Suggested changes have been updated, please review and approve.

**Review by mai93 — APPROVED** [review]

**Comment by cgruber** [comment]
I'm still getting this situation - I'm using 2024..3.3 uptimate edition, with bazel plugin 2025.01.21.0.2-api-version-243, and I get all the test fuzzing, and I get the "PASS ok" stuff from go test output, I still get "no tests were run" in the side panel
Screenshot 2025-02-18 at 1 57 29 PM

My particular structure may be different. I have:

/MODULE.bazel
/kotlin/...
/rust/...
/golang/Build.bazel
/golang/go.mod
/golang/brackets/Build.bazel
/golang/brackets/brackets.go
/golang/brackets/brackets_test.go

My IDE is set up with a bazel workspace at the root, and I added a content root of /golang so that all the IDE go stuff would resolve. I'm not sure if the test output is being written in a way that fools the plugin to not think there was any test output (so it reports no tests) or what.

**Comment by mai93** [comment]
@cgruber can you create a separate issue to track this problem?

**Comment by cgruber** [comment]
Sorry - this is not even the right issue, it's the changelog fix PR. Whoops. Opening a new issue.

**Pull request merged**
