### PR TITLE
Revert "Automatic code cleanup." - Remove dependency on rules_java

### PR DESCRIPTION
**Pull request by LeFrosch**
This reverts commit 697b9a9a9fe4d0b3c0672a694d8bbd3a5e5a5d4e.

# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [x] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: #6474

# Description of this change
It seems to be the case that if a project:
- depends directly or transitively on rules_java < 5.3.5 
- or uses bazel <= 6.3.2 

The project can no longer be synced because of an error like this:
```
ERROR: Traceback (most recent call last):
	File "<redacted>/external/intellij_aspect/intellij_info_impl_bundled.bzl", line 3, column 37, in <toplevel>
		load("@rules_java//java:defs.bzl", "JavaInfo", "java_common")
Error: file '@rules_java//java:defs.bzl' does not contain symbol 'JavaInfo'
```

I would suggest reverting this commit for now and to release a hotfix.

### CODE REVIEW

**Comment by mai93** [comment]
We added a note about this breaking change to the release notes https://github.com/bazelbuild/intellij/releases/tag/v2024.05.21-stable, do you think it is not enough?

**Comment by ujohnny** [comment]
> We added a note about this breaking change to the release notes https://github.com/bazelbuild/intellij/releases/tag/v2024.05.21-stable, do you think it is not enough?

We've received several reports also to JetBrains YouTrack about this issue, I assume we have to take some action based on this feedback. It's partially confusing to require `rules_java` in C++ projects, for example old `rules_java` version is coming from `googletest` dependencies IIUC.

**Comment by mai93** [comment]
@hvadehra will this load be mandatory in Bazel 8?

is there a way we can refactor the aspect code to not have this load for C++ workspaces? Until we figure this out we can rollback this commit

**Comment by hvadehra** [comment]
> @hvadehra will this load be mandatory in Bazel 8?

The plan currently is Bazel 8 will not contain these native rules/symbols, so yes, the loads will become necessary then.

Rollback SGTM for now.

> is there a way we can refactor the aspect code to not have this load

`load()` statements unfortunately can't be conditional. If we have different plugin releases by Bazel versions, we can to handle this in the packaging/release step for the plugin. Otherwise, ISTM the plugin may need to use different root bzl files (i.e. one with loads and one without) for the aspect(s) that will be conditioned on the Bazel version.

**Review by mai93 — APPROVED** [review]

**Pull request merged**
