### PR TITLE
Update to the published versions of IntelliJ

### PR DESCRIPTION
**Pull request by thunterdb**
Hello @brendandouglas ,
I know pull requests are currently discouraged, but I want to open this PR for the record. This is the version changes I had to do in order to build the code dump. The links in the workspace file are not valid anymore.

Tested on MacOS and Ubuntu.

### CODE REVIEW

**Comment by devoncarew** [comment]
@thunterdb, I had trouble building myself (the `bazel build //ijwb:ijwb_bazel` instructions from the readme weren't working). I patched in the first 2 lines from your PR and was able to build the plugin. Thanks for debugging this!

@brendandouglas, @tomlu, something worth patching it, or updating the code in the repo?

**Comment by brendandouglas** [comment]
Thanks for the PR @thunterdb, and sorry for the delay in replying.

At the moment this is just a code drop, but we're in the process of migrating to an active repository. Once this is complete, there should be regular updates.

If it looks like this process will take longer than a couple more weeks, we might do a second code dump (which would fix this issue, along with many other improvements).

In the meantime, the published plugin at https://plugins.jetbrains.com/plugin/8609 is being kept relatively up-to-date (one warning -- we had to change the plugin ID of the publicly available version, so if you want to download it from IntelliJ's public plugin repository, you'll need to uninstall any existing version first).

**Comment by thunterdb** [comment]
@brendandouglas thank you for the heads-up. I am looking forward to a public release in the future.

**Comment by brendandouglas** [comment]
This is now obsolete, as we've done a second code dump.

We're now planning to regularly update this project. At the moment we're building against 2016.2.1.

**Pull request closed without merging**
