### PR TITLE
support for clion 2020.2

### PR DESCRIPTION
**Pull request by sambercovici**
# Checklist

- [ x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [x ] I have received the approval from the maintainers to make this change.
- [x ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by sambercovici** [comment]
@googlebot I signed it!

**Comment by mistic** [comment]
@brendandouglas do you think you can take a look on this one?

**Comment by zhuker** [comment]
@sambercovici have you looked at clion 2020.3?
thanks for your work, i am using the plugin in 2020.2 and i am very happy about it :+1:

**Comment by russellsch** [comment]
Thanks much, needed 2020.2 to fix C++20 issues, this sorted me out!

**Comment by sambercovici** [comment]
looks like support for 2020.2 is available.

**Pull request closed without merging**
