### PR TITLE
Partial Intellij 2021.1 support

### PR DESCRIPTION
**Pull request by sitaktif**
# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [x] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

# Discussion thread for this change

Issue number: #2406

# Description of this change

- provide support for intelliJ 2021.1
- backward compatibility to build (but not test) until IntelliJ 2020.2

Caveats:
- no TypeScript support (may or may not work partially): APIs changed and I don't have the background to address that. 
- more work needed on the `sdkcompat/` side specifically to make testing work. I had to timebox the backward compatibility effort and unfortunately ran out of time. I may be able to go back to it later or maybe someone can pick up the work ; but in the meantime I thought opening this PR would be useful to the community.

The new version of this plugin has been tested successfully for a few days and no particular issues were spotted (but no guarantees as this is my first IJ plugin change!).

### CODE REVIEW

**Comment by AlexBurdu** [comment]
I cloned the forked repo and compiled the plugin am not able to install it in intellij ue 2021.1
```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-latest 
```
Intellij gives the following error when trying to install:
```
Plugin 'Bazel' (version '9999') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-211.6693.111
```

Also tried:
```
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-2021.1     
                                                      
INFO: Build option --define has changed, discarding analysis cache.
ERROR: /home/my_user/Projects/Cloned/bazel-intellij-2021.1/base/BUILD:40:24: Configurable attribute "plugin_xmls" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest
ERROR: Analysis of target '//ijwb:ijwb_bazel_zip' failed; build aborted: /home/my_user/Projects/Cloned/bazel-intellij-2021.1/base/BUILD:40:24: Configurable attribute "plugin_xmls" doesn't match this configuration: define an intellij product version, e.g. --define=ij_product=intellij-latest
INFO: Elapsed time: 0.140s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 120 targets configured)
```

**Comment by sitaktif** [comment]
Mmh that's weird, it works on laptop running on MacOS. Try with `bazelisk` just in case?

```
$ bazelisk build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-2021.1
INFO: Invocation ID: fa768ccd-246c-4e21-b2fd-fca1c2693ef2
INFO: Analyzed target //ijwb:ijwb_bazel_zip (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //ijwb:ijwb_bazel_zip up-to-date:
  bazel-bin/ijwb/ijwb_bazel.zip
INFO: Elapsed time: 0.340s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

$ git show-ref --head @
3a6e970892c4ffdd1fc52d3b1541a44867966951 HEAD

$ git status
HEAD detached at ghorigin/intellij-2021.1
nothing to commit, working tree clean
```

**Comment by AlexBurdu** [comment]
I ran it on Ubuntu 20.04.2 LTS.
```
bazel --version
bazel 4.0.0
```

**Comment by siberex** [comment]
@AlexBurdu use `intellij-2021.1` branch:

```
git remote add sitaktif git@github.com:sitaktif/intellij.git
git fetch sitaktif
git checkout sitaktif/intellij-2021.1
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-ue-2021.1
```

**Comment by AlexBurdu** [comment]
That worked.
Sorry, I wasn't paying much attention to the branch and assumed the change is on master.

**Comment by caseyduquettesc** [comment]
I have an Intellij 2021.1 branch that's up to date with master and builds community edition successfully (I don't own UE) and passes all the tests. Two assertions with the scala plugin had to be commented out because I didn't know how to fix.

I ran the following commands to test

```sh
bazel test //:ijwb_ce_tests --define=ij_product=intellij-2021.1
bazel test //:ijwb_ce_tests --define=ij_product=intellij-2020.3

bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-2021.1
bazel build //ijwb:ijwb_bazel_zip --define=ij_product=intellij-2020.3
```

Does someone want to update this PR or should I open a new one? I don't want to diminish all the work @sitaktif has already done, but my branch is here - 
https://github.com/bazelbuild/intellij/compare/master...caseyduquettesc:casey/intellij-2021.1

**Comment by sitaktif** [comment]
> I don't want to diminish all the work @sitaktif has already done

Absolutely not! This is great, thanks!

I'll try merging your changes in the next few days so we can have something that works with both UE/CE and that passes tests.

**Comment by alice-ks** [comment]
Thanks for having sent this PR. We considered some of the solutions suggested for the compatibility breakages of this PR when we eventually added the 2021.1 support to the plugin. By now, the plugin is even compatible with 2021.3.

**Pull request closed without merging**
