### PR TITLE
Bump to 2023.3 EAP

### PR DESCRIPTION
**Pull request by tpasternak**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by dkashyn-sfdc** [comment]
Are we there yet? I want to try 2023.3 EAP and no Bazel support is what is blocking me currently.

**Comment by ahmedyarub** [comment]
Tried building and installing this version but IntelliJ throws the following error in the logs and hangs:
```
SEVERE - #c.i.u.SlowOperations - Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
java.lang.Throwable: Slow operations are prohibited on EDT.
```

**Comment by ahmedyarub** [comment]
After the latest updates I can confirm that the plugin is working

**Comment by mai93** [comment]
is [ProjectIndexingHistoryWrapper.java](https://github.com/bazelbuild/intellij/blob/master/testing/testcompat/v232/com/google/idea/sdkcompat/indexing/ProjectIndexingHistoryWrapper.java) not needed?

**Review by mai93 — APPROVED** [review]

**Pull request merged**
