### PR TITLE
Pick up Kotlin version from rules_kotlin

### PR DESCRIPTION
**Pull request by szinn**
# Checklist

- [X] I have filed an issue about this change and discussed potential changes with the maintainers.
- [?] I have received the approval from the maintainers to make this change.
- [X] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `1274`

# Description of this change

This change gets the kotlin version from rules_kotlin (commit 242 - https://github.com/bazelbuild/rules_kotlin/commit/a3d4d561cc18680a510589772146c38e172ace65) and updates the ide_info such that Kotlin 1.3 functionality can be accessed if compiled with Kotlin 1.3

### CODE REVIEW

**Comment by brendandouglas** [comment]
Thanks, we can apply this upstream. It should go in aspect/intellij_info.bzl instead, as it's bazel-specific (doesn't apply to our internal build system, which has different kotlin rules)

**Comment by szinn** [comment]
@brendandouglas Does that mean you will apply the change or should I change the PR?

**Comment by szinn** [comment]
retest this please

**Comment by szinn** [comment]
@brendandouglas Any movement on this PR?

**Comment by cgruber** [comment]
Please can we get some eyes on this (@jin maybe?) Someone? We're nearly at Kotlin 1.4, and we still have the IDE re-configured to be at 1.2 every time we sync.  The kotlin rules are passing the information and this PR scoops that up and properly sets the language level. This is critical to a decent user experience.

**Comment by jin** [comment]
@brendandouglas is this good for import?

**Comment by DrewKiino** [comment]
bump - can we get this landed?

**Comment by szinn** [comment]
Bump again @brendandouglas @jin

**Comment by szinn** [comment]
@vsiva @chaoren @brendandouglas

**Comment by jin** [comment]
I've imported the PR. Please hold on for the internal review.

**Comment by DrewKiino** [comment]
nice!!!

**Comment by cgruber** [comment]
I'm so glad this is in. I'm having a heck of a time with coroutines. Thanks @jin !!

**Pull request closed without merging**
