### PR TITLE
Updating sha256 of python and scala

### PR DESCRIPTION
**Pull request by or-shachar**
# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Issue number: #2343

# Description of this change
Build is failing on 
`ERROR: /home/builduser/workspace/intellij-plugins-ci/intellij-check-and-notify-plugins-state/intellij/third_party/python/BUILD:7:13: //third_party/python:python_internal depends on @python_2020_1//:python in repository @python_2020_1 which failed to fetch. no such package '@python_2020_1//': java.io.IOException: Error downloading [https://plugins.jetbrains.com/files/7322/88054/python-ce-201.7846.93.zip] to /home/builduser/.cache/bazel/_bazel_builduser/1c03a469a8e977776a02273bfa495afd/external/python_2020_1/python-ce-201.7846.93.zip: Checksum was 648438d26e85072f90a62f9f5b9f9b983a49f3cb752e87d01f915cb6a03644b9 but wanted a3d7217794619dfa0432d922218dd875f49658939c6e5a54c01f99b333d35e12` 

and 

`Error in download_and_extract: java.io.IOException: Error downloading [https://plugins.jetbrains.com/files/1347/76628/scala-intellij-bin-2020.1.7.zip] to /home/builduser/.cache/bazel/_bazel_builduser/1c03a469a8e977776a02273bfa495afd/external/scala_2020_1/scala-intellij-bin-2020.1.7.zip: Checksum was 626b9c9bc2f90d64498524bd7138558edacf50bbc72a02f882401118a1fc1403 but wanted bbc019e7cde3baf21b11f0abde21f42d4606ca5ca9100b3bdace3292f70cceef`

Manually downloading from those URL reveals that the content has indeed changed :-/

### CODE REVIEW

**Comment by or-shachar** [comment]
@philwo  - question about BK - do we run on ephemeral machines or do builds share the same repository cache? If it's the latter - this can explain why builds are not failing in master right now.

**Comment by or-shachar** [comment]
@chaoren @vsiva ... any ack?

**Comment by philwo** [comment]
> do we run on ephemeral machines or do builds share the same repository cache

Linux machines are ephemeral and only run one CI job, then are deleted. macOS machines are persistent and the repository cache is being kept and reused over time.

**Comment by alice-ks** [comment]
Thanks for this PR. I imported it to our internal source of truth. #2371 is the re-export.

I think I can clarify the build situation: We only build the intellij-beta and intellij-ue-beta versions on CI. Those version variables currently point to 2020.3 for which we already fixed the checksums when the build failed.

**Comment by alice-ks** [comment]
Closing this PR as #2371 was merged.

**Pull request closed without merging**
