### PR TITLE
Trying to workaround "unsynced" case for newly added files.

### PR DESCRIPTION
**Pull request by dkashyn-sfdc**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change
https://github.com/bazelbuild/intellij/issues/5347

### CODE REVIEW

**Comment by mai93** [comment]
This can be fixed by running "Partial Sync" on the newly added file, can you explain why this fix is needed?

**Comment by dkashyn-sfdc** [comment]
Because when you refactoring/adding files, `unsynced` by default is confusing. 

Of course `Partial Sync` can help but:
 - it takes 1 minute for our project if you are lucky
 - with existing IJ project structure this operation is excessive so we can use sync status of surrounding files
 - it is so opaque and unapparent to our users that manual sync is required for every move/add operation

**Comment by blorente** [comment]
Sorry for the late review. The more I think about it, the more I am against this sort of change, because it will expose lies to users. 

I agree that we should have a lightweight way of updating the SourceToTargetMap for just one target that essentially expands the globs in `srcs`. Does `Bazel` -> `Sync` -> `Sync Directories` work for this case? It should be much faster, since it doesn't build anything with Bazel.

**Comment by dkashyn-sfdc** [comment]
@blorente, sorry for being a little bit blunt here, but we are having issues even with the first "Bazel Sync" need, with our engineers. This operation is so unnatural for IJ. 

"Sync" after any refactor or file changes might be okay, for Google with your huge project and associated tooling, but for mere mortals outside of Google, this is so unnatural that people are really struggling with this remedy.

Even more: a few of hundreds of our engs are fluent in all 5 types of syncs that Bazel Plugin has.

**Comment by dkashyn-sfdc** [comment]
Well, this was never 100%-complete solution since if the package is empty there is nothing to triangulate against.

Also if we are talking about tests there won't be consensus in packages for those.

**Comment by dkashyn-sfdc** [comment]
We decided not to proceed with this PR and to keep it to our internal version only :( I wish BSP were here faster!

**Pull request closed without merging**
