### PR TITLE
fix: Do not fail when setting a breakpoint in non-bazel project

### PR DESCRIPTION
**Pull request by blorente**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [X] I have received the approval from the maintainers to make this change.
- [X] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: Discovered internally.

# Description of this change

If opening a non-bazel project without importing it, setting a breakpoint used to make the Bazel plugin crash.

### CODE REVIEW

**Comment by mai93** [comment]
is this resolved by https://github.com/bazelbuild/intellij/commit/59ddcbe54739726f32e2953002d8a49d8f91c5cf?

**Comment by blorente** [comment]
Superseded by https://github.com/bazelbuild/intellij/commit/59ddcbe54739726f32e2953002d8a49d8f91c5cf

**Comment by ujohnny** [comment]
Actually the test looks nice, I think we anyway can merge this in.

**Comment by blorente** [comment]
@ujohnny Rebased and reopened in in https://github.com/bazelbuild/intellij/pull/5713

**Pull request closed without merging**
