### PR TITLE
Adding a ‘Copy target’ action to easily copy build targets from any element

### LINKED ISSUE #105: Copy belonging target label shortcut
Hi,
Is there a way to copy the target label a file belongs to? The idea is that many times when I want to add a dependency on a class I can use `CMD+N` to find the file and then `CMD+SHIFT+C` to copy the file path. From there it's a bit of fiddling to get the target name.
Is there a simpler way in the plugin?
It seems that you already know which target the file belongs to.

### PR DESCRIPTION
**Pull request by hmemcpy**
Fixes #105

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by hmemcpy** [comment]
Hey folks, hope you had a good holiday rest :)
Any chance you could look at this feature? Would make our lives easier if it were accepted!

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by brendandouglas** [comment]
Thanks for the patch, I'll apply it upstream. Apologies for the delay in getting to this

**Comment by hmemcpy** [comment]
No worries! Thanks a lot!
Feel free to close :)

**Pull request closed without merging**
