### PR TITLE
Simplify opening of Bazel project using ProjectUtil.

### PR DESCRIPTION
**Pull request by avshenuk**
# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: https://github.com/bazelbuild/intellij/issues/2147

# Description of this change

Shows a modal dialogue asking where to open the new Bazel project as with regular projects.

### CODE REVIEW

**Comment by tpasternak** [comment]
I know it's been a while, but it seems that the issue is not reproducible any more with IJ 2022.2

**Comment by avshenuk** [comment]
@sgowroji Yes, the status bar is not broken anymore. Thank you!

So the only feature this PR adds now is a modal dialogue asking which window the project should be opened in (current or new, as with regular projects). 
But you can close it if you think it's not worth it.

**Comment by tpasternak** [comment]
Right, let's take it then!

**Comment by mai93** [comment]
Thank you @avshenuk. Can you please rebase the PR for the CI tests to pass? Please check the [error](https://buildkite.com/bazel/android-studio-plugin/builds/17333#01838079-3acc-4600-89ed-d70359c81416)

**Comment by avshenuk** [comment]
@mai93 Done :)

**Comment by tpasternak** [comment]
Thank you @avshenuk

**Pull request merged**
