### PR TITLE
Update changelog for 2024.09.24 release

### PR DESCRIPTION
**Pull request by satyanandak**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by mai93** [comment]
> please hold one, we need to push this to beta as a hotfix [02ad803](https://github.com/bazelbuild/intellij/commit/02ad803fb8ab184e8a6131312e2fc6aabc2bae82)

released v2024.09.10.0.3 with this fix to beta channel

**Comment by mai93** [comment]
### Bug Fixes
- Fix auto-import exception [#6753](https://github.com/bazelbuild/intellij/pull/6753)
- https://github.com/bazelbuild/intellij/pull/6756
- https://github.com/bazelbuild/intellij/pull/6748

### Features
- CLion add support for `additional_compiler_inputs` [#6774](https://github.com/bazelbuild/intellij/pull/6774)

**Comment by mai93** [comment]
@mtoader is https://github.com/bazelbuild/intellij/issues/6664 ready to be announced in this release?

**Comment by mtoader** [comment]
> @mtoader is #6664 ready to be announced in this release?

I would phrase it like this: 

```Markdown
Added completion support for external targets from modules. Needs `--incompatible_use_plus_in_repo_names` set (defaults to true in bazel 8.0+) to work optimally.
```

**Review by mai93 — APPROVED** [review]

**Pull request merged**
