### PR TITLE
Fix package_group typo

### PR DESCRIPTION
**Pull request by TastyPi**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by TastyPi** [comment]
I signed it!

**Comment by brendandouglas** [comment]
Thank you for the fix! (and apologies for the CLA spam).

We're not yet set up to accept pull requests here; it's currently just a code drop for educational purposes.

I'll apply your fix upstream, and it should be in the next code drop.

**Pull request closed without merging**
