### PR TITLE
Update bazel version to Bazel 8.0.0rc7

### PR DESCRIPTION
**Pull request by hvadehra**
The workaround in WORKSPACE.bzlmod is needed for the hybrid bzlmod+workspace mode, since rules_scala depends on rules_java. Repos declared by rules_java (with bzlmod) are not automatically visible to WORKSPACE repositories.

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: https://github.com/bazelbuild/intellij/issues/7058

# Description of this change

### CODE REVIEW

**Comment by hvadehra** [comment]
cc @tpasternak CI seems to be happy with this, are there more workflows that need to be executed with this?

**Comment by tpasternak** [comment]
Hi, we still have this one https://github.com/bazelbuild/intellij/pull/7111#issuecomment-2517660327

**Comment by hvadehra** [comment]
Looks like that was caused by https://github.com/bazelbuild/bazel/commit/489d08bf472f4568b3f7f478a8747a30cb956111 ,  updated .bazelrc which makes the issue go away.

**Comment by tpasternak** [comment]
Oh, thank you! Just to be 100% clear, @LeFrosch can you take a look?

**Comment by LeFrosch** [comment]
@tpasternak I'll check this first thing tomorrow

**Comment by hvadehra** [comment]
I filed https://github.com/bazelbuild/bazel/issues/24578 to track fixing things in Bazel and updated the comment in `.bazelrc`

**Comment by LeFrosch** [comment]
Thanks looks good #7126

**Review by LeFrosch — APPROVED** [review]

**Pull request merged**
