### PR TITLE
fix: disable bzlmod for"with_go_source" example

### PR DESCRIPTION
**Pull request by tpasternak**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by mai93** [comment]
is the plugin failing to support bzlmod for this project?

**Comment by blorente** [comment]
I think this is not a plugin issue, but rather a project issue. As it stands the project is not bzlmod-compatible (running `bazel run //:gazelle` fails). Maybe we can just disable bzlmod in the `.bazelrc` instead of the project file and make it compatible later

**Review by blorente — APPROVED** [review]
Approving to unblock merging, but we definitely should either make the project bzlmod-compatible or move the flag to `.bazelrc`.

**Comment by tpasternak** [comment]
But it's only because we have `--enable_bzlmod` in the root .bazelrc

**Comment by tpasternak** [comment]
oh, wait, I'm wrong

**Pull request merged**
