### PR TITLE
fix: Disable python codegen support by default

### PR DESCRIPTION
**Pull request by tpasternak**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by tpasternak** [comment]
@agluszak

**Review by agluszak — APPROVED** [review]

**Comment by FrankPortman** [comment]
I happened to see this PR when browsing this PR and this change looks potentially significant to me as I have macros/rules that generate `PyInfo`/files -> `py_library` in my codebase. Is there any documentation for this change?

**Comment by andponlin-canva** [comment]
> I happened to see this PR when browsing this repo and this change looks potentially significant to me as I have macros/rules that generate `PyInfo`/files -> `py_library` in my codebase. Is there any documentation for this change?

Hello @FrankPortman ; I added some comments [here](https://github.com/bazelbuild/intellij/blob/master/docs/python/code-generators.md) which also includes an example.

**Comment by FrankPortman** [comment]
Thanks - if my understanding is correct then this flag and tag are required to make IntelliJ properly detect and remove the "red squiggle" from codegenned files. But my basic usage of both macros and rules to code generate Python files has not had issues with IntelliJ as of now. Is this change a general safety net or only needed if you intend to output directories rather than marking individual files?

**Comment by andponlin-canva** [comment]
Yes the flag and tag will be required to make this work fully. The intention is to remove the "red squiggle" (see [here](https://github.com/bazelbuild/intellij/issues/6725#issuecomment-2389649698)) and to allow code-complete on generated code.

**Comment by andponlin-canva** [comment]
> But my basic usage of both macros and rules to code generate Python files has not had issues with IntelliJ as of now

@FrankPortman ; If I understand you correctly, you are facading your Rules' files-based (no directory) output with a `py_library` which is working for you in Intelli-J? This change presumes that you might be using the Rule directly and the Rule has the option of having directory-based outputs. This may be the two differences from the approach that you have.

**Comment by FrankPortman** [comment]
Thank you - that does sound like the distinction.

**Pull request merged**
