### PR TITLE
Support for IJ 2020.3

### PR DESCRIPTION
**Pull request by shs96c**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

# Discussion thread for this change

Issue number: #2102 

# Description of this change

This change drops support for 2020.1, and in its place adds support for 2020.3. 

Dropping support for 2020.1 was done in order to simplify the number of places that needed to be updated or changed, but it should be trivial to back that out of this PR if necessary.

### CODE REVIEW

**Comment by alice-ks** [comment]
Thanks for working on the compatibility with 2020.3. I didn't have time for a full review yet but I noticed that you dropped the 2020.1 support. Unfortunately, we still need the compatibility with 2020.1 (and even 2019.3 for CLion). Can you please add it back?

**Comment by nicknezis** [comment]
I am looking forward to this being merged and released. @shs96c is there anything I can do to help?

**Comment by c16a** [comment]
@shs96c are you still working on this?

**Comment by shs96c** [comment]
Not over the holidays :)

**Comment by illera88** [comment]
Hey @shs96c 

thanks for the PR. Can it be already used even if it is not merged?

**Comment by shs96c** [comment]
This needs rebasing, but it could be used when I submitted it. When I get a chance, I'll do so and respond to the review comment about leaving in support for IJ 2020.1

**Comment by illera88** [comment]
Thank you @shs96c . Looking forward to this!

**Comment by illera88** [comment]
I've tried to build your changes and I get:
```
$ bazel build //clwb:clwb_bazel_zip --define=ij_product=clion-latest
INFO: Repository jarjar instantiated at:
  /home/user/Documents/code/bazel-intellij/WORKSPACE:236:26: in <toplevel>
  /home/user/.cache/bazel/_bazel_user/56942b33bc8dbd16ebb2ad1b7be140d7/external/bazel_tools/tools/build_defs/repo/jvm.bzl:285:24: in jvm_maven_import_external
Repository rule jvm_import_external defined at:
  /home/user/.cache/bazel/_bazel_user/56942b33bc8dbd16ebb2ad1b7be140d7/external/bazel_tools/tools/build_defs/repo/jvm.bzl:217:38: in <toplevel>
ERROR: /home/user/Documents/code/bazel-intellij/third_party/javascript/BUILD:46:13: no such package '@intellij_ue_2019_3//': The repository '@intellij_ue_2019_3' could not be resolved and referenced by '//third_party/javascript:angular_internal'
ERROR: Analysis of target '//clwb:clwb_bazel_zip' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.275s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 7 targets configured)
    Fetching @clion_2019_3; fetching
    Fetching @bazel; fetching
    Fetching @remotejdk11_linux; fetching
```

**Comment by AlexeyGy** [comment]
Thanks again for creating this, we have by now added support for 2020.3 in a beta release. Which you can now also install in IntelliJ https://github.com/bazelbuild/intellij/issues/2102 

Please do not feel like this PR was in vain! When implementing the changes, I had looked at your suggestions and found them very helpful. Unfortunately, due to the nature of the code partly living on our internal repository, we cannot merge PRs easily at the moment. We have plans to improve this in the future.

**Comment by nicknezis** [comment]
I'm not able to update my IntelliJ to 2020.3 yet on OSX. Is the plugin update released? Or do I need to do something to get the beta plugin?

**Pull request closed without merging**
