### PR TITLE
ui: "Bazel Problems" not "Blaze Problems"

### PR DESCRIPTION
**Pull request by JensRantil**
- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

Issue number: #1042

...in the title of listed problem. Since the plugin is called "Bazel" I assume users will be surprised when it says Blaze.

### CODE REVIEW

**Comment by jin** [comment]
Unfortunately this would not work, because the string would change internally to "Bazel Problems".

What you probably want to do here is an instance method to replace the `TOOL_WINDOW_ID` constant to:

```java
  public String getToolWindowId() {
    return Blaze.getBuildSystem(project).getName() + " Problems";
  }
```

**Comment by jin** [comment]
also please sign the CLA :)

**Comment by jin** [comment]
Hey, any updates on this PR?

**Comment by JensRantil** [comment]
> also please sign the CLA :)

Extremelly late feedback here. I had signed the CLA, or did I miss something?

Screenshot 2019-11-24 at 22 16 29

**Pull request closed without merging**
