### PR TITLE
chore: Remove examples from bazelignore

### PR DESCRIPTION
**Pull request by tpasternak**
It seems to affect Renovate

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by ujohnny** [comment]
Shouldn't we even add more to it (ignore integration testdata) rather that remove it completely? cc @LeFrosch

**Comment by tpasternak** [comment]
I'm not sure, but Renovate seems to ignore these directories

**Comment by LeFrosch** [comment]
@ujohnny Integration test data cannot be ignored since they need to be accessed by the tests at runtime as far as I understand. They are “deleted packages”, see .bazelrc.

**Comment by tpasternak** [comment]
So can I remove that, I don't even really see the point of it, while it seems that Revovate fails to upgrade projects there

**Review by sellophane — APPROVED** [review]

**Pull request merged**
