### PR TITLE
Add support for dot in target name

### PR DESCRIPTION
**Pull request by stle85**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: 4431

# Description of this change

### CODE REVIEW

**Comment by sgowroji** [comment]
Hi @stle85, Could you please sign the [CLA](https://github.com/bazelbuild/intellij/pull/4432/checks?check_run_id=11283051360). Thanks!

**Comment by stle85** [comment]
Hi @sgowroji
I've signed the CLA

**Comment by stle85** [comment]
Hi @sgowroji 
Do I need re-run pipeline?
If yes could you help with understanding how to do this.

**Comment by raoarun** [comment]
assigned to blorente.

**Comment by blorente** [comment]
Thanks for the contribution!
The change looks great, but ould you add a test to [this file]( https://github.com/bazelbuild/intellij/blob/master/base/tests/unittests/com/google/idea/blaze/base/run/filter/BlazeTargetFilterTest.java#L29) to make sure the issue you're facing never happens again?

**Comment by blorente** [comment]
Closing as the full set of valid characters has since been implemented

**Pull request closed without merging**
