### PR TITLE
Run aswb tests on macos arm64

### PR DESCRIPTION
**Pull request by Bencodes**
Adding some mac os CI validation to help find edge cases like https://github.com/bazelbuild/intellij/pull/5322

### CODE REVIEW

**Comment by mai93** [comment]
Thanks @Bencodes! Can you also add one for the [`google` branch CI configuration](https://github.com/bazelbuild/intellij/blob/google/.bazelci/android-studio.yml)?

**Review by mai93 — APPROVED** [review]

**Comment by Bencodes** [comment]
Opened up a PR here https://github.com/bazelbuild/intellij/pull/5326

**Comment by mai93** [comment]
I think you can rebase this PR now that https://github.com/bazelbuild/intellij/commit/6b5743eac511d50d31f88042acb66f46f1ca03f7 is in.

**Comment by Bencodes** [comment]
This branch has been rebased.

**Comment by mai93** [comment]
Some tests are failing on mac, I added (help needed) tag if anyone wants to help us fix them.

**Pull request closed without merging**
