### PR TITLE
Update changelog for v2024.09.10 release

### PR DESCRIPTION
**Pull request by satyanandak**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by mai93** [comment]
### Bug Fixes
- https://github.com/bazelbuild/intellij/pull/6693
- https://github.com/bazelbuild/intellij/pull/6741

**Review by mai93 — APPROVED** [review]

**Comment by tpasternak** [comment]
Hey, we are releasing external labels indexing and completions, thanks to @mtoader

**Comment by tpasternak** [comment]
We didn't have such a tradition, however this contribution is so great, I would consider giving credits, WDYT? @mai93

**Comment by mai93** [comment]
> We didn't have such a tradition, however this contribution is so great, I would consider giving credits, WDYT? @mai93

I agree, feel free to propose a suggestion on the comment. Thanks @mtoader!

**Comment by tpasternak** [comment]
so maybe let's just add `credits: @mtoader (https://github.com/mtoader)`?

**Comment by tpasternak** [comment]
idk how about just `(credits:  )`

**Comment by mtoader** [comment]
That still doesn't work well without the bazel flag changing `~` to `+` (the one becoming default true in bazel 8). So it will be limited in exposure until i have the notification in place to have the users update said flag. 

Also the more important bit is https://github.com/bazelbuild/intellij/pull/6742 (since it enabled completion past the `@xxx//` in these cases :) i would mention this issue after we land this and add the notification bubble since that will be a "proper" user experience.

**Comment by mai93** [comment]
thanks @mtoader for the clarification, @satyanandak can you remove the "Features" part before submitting?

**Pull request merged**
