### PR TITLE
Update changelog for v2024.11.05 release

### PR DESCRIPTION
**Pull request by satyanandak**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by tpasternak** [comment]
I would really like to have these two merged

- https://github.com/bazelbuild/intellij/pull/6962
- https://github.com/bazelbuild/intellij/pull/6964

**Comment by tpasternak** [comment]
- https://github.com/bazelbuild/intellij/pull/6911
- https://github.com/bazelbuild/intellij/pull/6925
- https://github.com/bazelbuild/intellij/pull/6919
- https://github.com/bazelbuild/intellij/pull/6891
- https://github.com/bazelbuild/intellij/pull/6941
- https://github.com/bazelbuild/intellij/pull/6938
- https://github.com/bazelbuild/intellij/pull/6944
- https://github.com/bazelbuild/intellij/pull/6922
- https://github.com/bazelbuild/intellij/pull/6960
- https://github.com/bazelbuild/intellij/pull/6964
- https://github.com/bazelbuild/intellij/pull/6962
- https://github.com/bazelbuild/intellij/pull/6967

**Comment by tpasternak** [comment]
@satyanandak please hold on, still one of the PRs is not merged

**Comment by satyanandak** [comment]
@tpasternak sure noted, I will add those PRS as well once it is merged.

**Comment by tpasternak** [comment]
Ok @satyanandak let's continue


Also, the current beta channel version throws an annoying NPE. Can we port https://github.com/bazelbuild/intellij/pull/6960 before promoting it to stable?

**Review by mai93 — APPROVED** [review]

**Comment by satyanandak** [comment]
@tpasternak,  #6952  has been chery picked to stable.

**Pull request merged**
