### PR TITLE
Include implicit dependencies from proto compilers

### PR DESCRIPTION
**Pull request by fkorotkov**
# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [x] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Description of this change

`go_proto_library` has compilers which bring some types implicitly. Let's not forget to include them.

### CODE REVIEW

**Comment by fkorotkov** [comment]
Here are the [`compilers` in question from `rules_go`](https://github.com/bazelbuild/rules_go/blob/bd44f4242b46e73fb2a81fc87ea4b52173bde84e/proto/compiler.bzl#L44-L46).

**Comment by fkorotkov** [comment]
@alice-ks gentle ping

**Comment by fkorotkov** [comment]
@alice-ks 2022.1 is in beta now. I think it might be a good time to merge some changes to `intellij_info_impl.bzl`. Could you please take a look?

**Comment by tpasternak** [comment]
LGTM

**Comment by fkorotkov** [comment]
@sgowroji please check "Description of this change" that I had and let me know if it needs more details.

**Comment by fkorotkov** [comment]
I didn't see any tests for other `DEPS` back 7 months ago when I opened the PR. Now I have other things on my plate and don't have time in the near future to work on adding such tests. Closing the PR until then.

**Comment by jastice** [comment]
I think the query was as to how we can verify it, not to add specific tests. Was that the intention, @sgowroji ?

**Comment by fkorotkov** [comment]
My bad with the initial description which doesn't clarify "some types" but I guess [there sources](https://github.com/bazelbuild/rules_go/blob/10e90ba5c1de303db435c03aa3e3e876a8731622/proto/def.bzl#L123-L129) is what I meant. If I recall correctly there were some issue with the plugin not being able to resolve some well known types.

**Review by blorente — APPROVED** [review]
Thanks for the contribution! Looks good, I just hope no other ruleset defines the attribute `compilers` :D As it stands, this is the best way to solve it.

**Review by jastice — APPROVED** [review]

**Pull request merged**
