### PR TITLE
Update changelog for v2024.10.08 release

### PR DESCRIPTION
**Pull request by satyanandak**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by tpasternak** [comment]
Please merge this before release

**Comment by mai93** [comment]
## Bug Fixes
- https://github.com/bazelbuild/intellij/pull/6759
- Fixes for Query Sync (ready to use): [#6833](https://github.com/bazelbuild/intellij/pull/6833), [#6834](https://github.com/bazelbuild/intellij/pull/6834), [#6835](https://github.com/bazelbuild/intellij/pull/6835), [#6841](https://github.com/bazelbuild/intellij/pull/6841)
- https://github.com/bazelbuild/intellij/pull/6839
- https://github.com/bazelbuild/intellij/pull/6853

## Features
- https://github.com/bazelbuild/intellij/pull/4473

**Review by mai93 — APPROVED** [review]

**Comment by tpasternak** [comment]
@mai93 how about cutting a release for 2024.3, too?

**Comment by mai93** [comment]
I created https://github.com/bazelbuild/intellij/tree/v2024.10.08 and release for 2024.3 from there https://plugins.jetbrains.com/plugin/8609-bazel-for-intellij/versions/stable/616084 also for CLion but it is pending verification

**Pull request merged**
