### PR TITLE
Update CHANGELOG  for 2024.11.19 release

### PR DESCRIPTION
**Pull request by tanishktyagii**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by tpasternak** [comment]
Features
- Bazel Icon for Plugin Logo `#6973`
- Query Sync: "Enable analysis" widget for Remote Development `#6996`
- Starlark Debuger: Gutter icons to start debugging `#6999`

Fixes: 
- C++: Do not collide with CMake `#6770`
- https://github.com/bazelbuild/intellij/pull/6985
- Query Sync:  Fix NPE when enabling analysis for a directory `#6992`
- Bazel 8 support for Java (`#6987` and `#7006`)

Also, please do not release until this is fixed:
- #7009

**Comment by tpasternak** [comment]
Ok, we also need to wait for this:
- https://github.com/bazelbuild/intellij/pull/7027

**Comment by ujohnny** [comment]
also we need this fix #7029

**Comment by tpasternak** [comment]
@tanishktyagii we're ready!

**Review by mai93 — APPROVED** [review]

**Comment by tpasternak** [comment]
@tanishktyagii could you pleas split the changelog into "Features" and "Fixes" section?

**Pull request merged**
