### PR TITLE
Import Bazel protos using their repo relative path.

### PR DESCRIPTION
**Pull request by lberki**
This idiom broke in Bazel@HEAD due to 50013dd.

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by or-shachar** [comment]
Already have it in #2181

**Comment by lberki** [comment]
That works, too. Are you merging that one?

**Comment by or-shachar** [comment]
I wish I had the permissions... 😔

**Comment by chaoren** [comment]
I've merged the copybara change to fix this, but it looks like that'll only take affect after some other CL triggers a migration. In the mean time I'll just merge this manually, the next CL should merge cleanly with this.

**Comment by or-shachar** [comment]
What about not depending on bazel head? it's a huge break to reproducibility...

**Pull request merged**
