### PR TITLE
Update changelog for 2024.02.27 release

### PR DESCRIPTION
**Pull request by rakshitasingh05**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by mai93** [comment]
- https://github.com/bazelbuild/intellij/pull/6094
- https://github.com/bazelbuild/intellij/pull/6127
- https://github.com/bazelbuild/intellij/pull/6158

**Comment by mai93** [comment]
@rakshitasingh05 can you please not merge just yet?

@ujohnny do you want to move 24.1 before we cut this release?

**Comment by ujohnny** [comment]
> @ujohnny do you want to move 24.1 before we cut this release?

yes I'd be happy to merge it before the cut

**Comment by rakshitasingh05** [comment]
@mai93 As I can see the above request from @ujohnny is being merged, so can I merge this PR now?

**Comment by mai93** [comment]
yes, please proceed with the release

**Pull request merged**
