### PR TITLE
Update changelog for v2024.07.02 release

### PR DESCRIPTION
**Pull request by satyanandak**
Please let me know of any important changes that you want to make visible by adding to the Change log.

### CODE REVIEW

**Comment by tpasternak** [comment]
Bug fixes:
- #6502 
- #6534 
- #6521 
- #6538 
- #6537

Performance fix:
- #6508

Internal changes:
- #6494

**Comment by tpasternak** [comment]
@satyanandak please remember not to put #6537 in changelog if it is not merged at the time

**Comment by satyanandak** [comment]
@tpasternak noted ! and also can you confirm, shall I put along with the headings as you mentioned ?

**Comment by tpasternak** [comment]
When come to headings it's up to you. To me it looks more readable with the headings

**Review by mai93 — APPROVED** [review]

**Comment by mai93** [comment]
@satyanandak  https://github.com/bazelbuild/intellij/pull/6537 is not merged yet

**Pull request merged**
