### PR TITLE
[WIP] contrib module to sync proto import roots settings into the protobuf

### PR DESCRIPTION
**Pull request by hsyed**
plugin.

see [readme](https://github.com/bazelbuild/intellij/compare/master...hsyed:contrib_proto_settings_sync?expand=1#diff-aa897479c90871cb50a1357b76086e34) for description.

### CODE REVIEW

**Comment by hsyed** [comment]
@brendandouglas wdyt about this pr ?

**Comment by hsyed** [comment]
@brendandouglas @chaoren I'd really like to get this in -- This PR has been around for a long time. 

Could you give it a look. The workspace resolution algorithm needs a tidy I think since I wrote it in one sitting -- if everything else is ok I can productionise the PR.

At the time it wrote this it configured the Protobuf Lang plugin with all of our local and external workspace proto paths correctly (7 in total).

I've created a contrib directory for the community to add non-core plugins.  This could be excluded from Google internal builds, but included in IJ / IJ-UE and Goland which really need something like this.

**Comment by hsyed** [comment]
Tidied up and updated for current codebase.

**Comment by brendandouglas** [comment]
@hsyed, thanks for the PR. I'm not sure what to do about this yet -- we have a proto plugin we use internally, integrated with this plugin. We've been planning to open source it, but haven't yet (personally I've found it way more useful than the 'Protobuf Support' plugin).

So currently this PR would cause confusion internally, and may make eventual open-sourcing of our other plugin more difficult.

**Comment by sgowroji** [comment]
Hello @hsyed, Could you please resolve the conflicts i can share it for review. Thanks!

**Comment by hsyed** [comment]
@sgowroji This PR was opened a lifetime ago. I no longer have any context. Shall I close it ?

**Comment by sgowroji** [comment]
Thank you for the update.

**Pull request closed without merging**
