### PR TITLE
fix: Rely on the bazel zipper instead of zip

### PR DESCRIPTION
**Pull request by blorente**
# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [X] I have received the approval from the maintainers to make this change.
- [X] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

N/A

# Description of this change

Not all environments have `zip` in their path. For instance, some Remote Execution environments like to have very lean workers. Furthermore, we shouldn't rely on all environments having the same version. We replace zip with the bazel jar handler.

We have been using this change internally to build the plugin against our build environment for a few months now.

### CODE REVIEW

**Review by agluszak — APPROVED** [review]
It's a pity that the bazel zipper requires so many additional steps, but I think it's worth it.

**Comment by blorente** [comment]
Yeah, it wasn't my happiest PR to write 😅 . There are java tools like jarjar which can do this, but I erred on the side of not introducing another dependency.

**Comment by tpasternak** [comment]
ok, now we have #6468

**Comment by blorente** [comment]
I’ll get on this right now.

**Pull request merged**
